name: douban movie sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        MOVIE_NOTION_TOKEN: ${{ secrets.MOVIE_NOTION_TOKEN }}
        NOTION_MOVIE_URL: ${{ secrets.NOTION_MOVIE_URL }}
        DOUBAN_NAME: ${{ secrets.DOUBAN_NAME }}
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: douban movie sync
        run: |
          douban "movie"
